timezone: Asia/Shanghai

# Site settings
title: yewen.me
email: i@yewen.me
description: > # this means to ignore newlines until "baseurl:"
  A jekyll drive site running on github pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yewen.me" # the base hostname & protocol for your site
twitter_username: whusnoopy
github_username:  whusnoopy

# Build settings
markdown: kramdown
